# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3177ff7a7e024411de96458f93fbb9840449fe217c84c1da96c14fdb9c7089ac13ec2411aa95c42ec7c47a8956de27cbe9c119bc2e3740f57446566ebafb7a4d

test:
  secret_key_base: d49395a378adb363d90489b22c1c6a007c336c048289bdfefa01d9fe65ae12a5fb78257ed49637715091a2ccf3875e7f551d5a41a6b7512c0151f4d76ceb7f0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
